# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.2.0
_src_path: git@github.com:MeteoSwiss-APN/mch-python-blueprint.git
email: tobias.wicky@meteoswiss.ch
full_name: Tobias Wicky
github_username: twicki
module_name: demo_project
project_github: twicki/demo-project
project_name: demo project
project_short_description: Tobias Wicky's demo project
project_slug: demo-project
python_version: '3.10'
version: 0.1.0
year: '2022'

